<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Troubleshooting — UPLINK Docs</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="css/docs.css">
</head>
<body>
  <header class="topbar">
    <a href="/" class="logo">⬡ UPLINK DOCS</a>
    <nav class="topnav">
      <a href="/">Home</a>
      <a href="features.html">Features</a>
      <a href="configuration.html">Config</a>
      <a href="https://github.com/mooncompany/uplink" target="_blank">GitHub</a>
    </nav>
    <button class="hamburger" id="hamburger" aria-label="Menu">
      <span></span><span></span><span></span>
    </button>
  </header>

  <div class="docs-layout">
    <aside class="sidebar">
      <div class="sidebar-section">
        <div class="sidebar-title">Getting Started</div>
        <a href="getting-started.html">Installation</a>
        <a href="configuration.html">Configuration</a>
        <a href="cli.html">CLI Reference</a>
      </div>
      <div class="sidebar-section">
        <div class="sidebar-title">Features</div>
        <a href="features.html">Overview</a>
        <a href="voice-chat.html">Voice Chat</a>
        <a href="agents.html">Agents</a>
        <a href="artifacts.html">Artifacts</a>
        <a href="split-view.html">Split View</a>
        <a href="remote-access.html">Remote Access</a>
        <a href="themes.html">Themes</a>
      </div>
      <div class="sidebar-section">
        <div class="sidebar-title">Reference</div>
        <a href="commands.html">Commands</a>
        <a href="premium.html">Premium</a>
        <a href="faq.html">FAQ</a>
      </div>
      <div class="sidebar-section">
        <div class="sidebar-title">Support</div>
        <a href="troubleshooting.html" class="active">Troubleshooting</a>
      </div>
    </aside>

    <main class="docs-content">
      <h1>Troubleshooting</h1>
      <p class="subtitle">Common issues and how to fix them. Can't find your problem? Open an issue on GitHub.</p>

      <h2>Server Won't Start</h2>

      <h3>Port Already in Use</h3>
      <p>If you see <code>Error: EADDRINUSE :::3456</code>, another process is using port 3456.</p>

      <div class="code-block">
        <div class="code-block-header">
          <span>bash</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code># Find what's using the port
# Windows:
netstat -ano | findstr :3456

# macOS/Linux:
lsof -i :3456

# Option 1: Kill the conflicting process
# Option 2: Use a different port
PORT=3457 node server.js</code></pre>
      </div>

      <h3>Node.js Version Too Old</h3>
      <p>Uplink requires Node.js v18 or later. Check your version:</p>

      <div class="code-block">
        <div class="code-block-header">
          <span>bash</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code>node --version
# If below v18, update from https://nodejs.org</code></pre>
      </div>

      <h3>Missing Dependencies</h3>
      <p>If you see <code>MODULE_NOT_FOUND</code> errors, your <code>node_modules</code> may be incomplete:</p>

      <div class="code-block">
        <div class="code-block-header">
          <span>bash</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code># Delete and reinstall dependencies
rm -rf node_modules
npm install</code></pre>
      </div>

      <h3>Sharp Install Fails</h3>
      <p><a href="https://sharp.pixelplumbing.com" target="_blank">Sharp</a> is an optional dependency used for image compression. If it fails to install with native build errors, that's OK — Uplink works fine without it. Images will just be sent at their original size.</p>
      <p>If you want image compression and Sharp won't install:</p>
      <ul>
        <li><strong>macOS:</strong> <code>xcode-select --install</code> to get build tools, then retry <code>npm install sharp</code></li>
        <li><strong>Windows:</strong> Install <a href="https://visualstudio.microsoft.com/visual-cpp-build-tools/" target="_blank">Visual C++ Build Tools</a>, then retry</li>
        <li><strong>Linux / WSL2:</strong> <code>sudo apt install build-essential</code>, then retry</li>
        <li><strong>Still failing:</strong> Skip it. Everything else works without Sharp.</li>
      </ul>

      <h2>Messages Not Working</h2>

      <h3>Gateway Connection Failed</h3>
      <p>If the UI loads but messages fail with a connection error, Uplink can't reach the OpenClaw gateway.</p>
      <ul>
        <li>Check that OpenClaw is running: <code>openclaw gateway status</code></li>
        <li>Verify the Gateway URL in Settings → Connection matches your OpenClaw setup</li>
        <li>Default gateway URL is <code>http://127.0.0.1:18789</code></li>
        <li>Try opening the gateway URL in your browser — you should see a JSON response</li>
      </ul>

      <h3>Slow or Hanging Responses</h3>
      <p>If messages take a very long time or seem to hang:</p>
      <ul>
        <li>The AI model may be loading — first message after startup is always slower</li>
        <li>Check your model's resource requirements vs. your hardware</li>
        <li>Open the browser's developer console (F12) to see if there are WebSocket errors</li>
        <li>Try reducing the context window or switching to a smaller model</li>
      </ul>

      <h2>Voice Chat Issues</h2>

      <h3>TTS Not Working</h3>
      <p>If you don't hear voice responses:</p>
      <ol>
        <li>Check Settings → Voice to confirm a TTS engine is selected</li>
        <li>If using Edge TTS: Make sure you have internet access and <code>node-edge-tts</code> is installed</li>
        <li>If using XTTS: Verify the XTTS server is running and the URL is correct (default: <code>http://localhost:8020</code>)</li>
        <li>If using OpenAI TTS: Verify your API key is valid</li>
        <li>If using ElevenLabs: Verify your API key is valid and you have remaining quota</li>
        <li>If using Piper: Verify <code>PIPER_MODEL</code> points to a valid <code>.onnx</code> model file</li>
        <li>Check browser audio permissions — Uplink needs permission to play audio</li>
      </ol>

      <div class="code-block">
        <div class="code-block-header">
          <span>bash</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code># Test your XTTS server directly
curl http://localhost:8020/api/tts -X POST \
  -H "Content-Type: application/json" \
  -d '{"text": "Hello", "language": "en"}' \
  --output test.wav

# If this fails, the issue is with your XTTS server, not Uplink</code></pre>
      </div>

      <h3>STT Not Working (Microphone)</h3>
      <p>If voice input doesn't transcribe:</p>
      <ul>
        <li>Check browser microphone permissions — the browser must allow access</li>
        <li>If using faster-whisper: Verify the server is running and URL is correct in Settings → Voice &amp; TTS</li>
        <li>If using OpenAI Whisper STT: Verify your OpenAI API key is valid and has remaining credits</li>
        <li>If using Groq STT: Verify your Groq API key is valid and the Groq service is reachable</li>
        <li>If using Browser STT: Make sure you're using Chrome or Edge — Firefox and Safari have limited Web Speech API support</li>
        <li>On mobile: Make sure the PWA has microphone permissions in your device settings</li>
        <li>On mobile over Tailscale: Use the HTTPS URL (<code>https://...ts.net:3457</code>) — browsers require HTTPS for microphone access</li>
      </ul>

      <h3>Voice Latency Too High</h3>
      <p>If there's a long delay between speaking and hearing a response:</p>

      <div class="table-wrap">
        <table>
          <thead>
            <tr><th>Bottleneck</th><th>Fix</th></tr>
          </thead>
          <tbody>
            <tr><td>STT too slow</td><td>Use a smaller Whisper model (tiny or base instead of medium)</td></tr>
            <tr><td>AI response slow</td><td>Use a faster/smaller model, or check GPU utilization</td></tr>
            <tr><td>TTS too slow</td><td>Switch from XTTS to Edge TTS, or use a GPU with more VRAM</td></tr>
            <tr><td>Network latency</td><td>If using cloud TTS, latency depends on your internet speed</td></tr>
          </tbody>
        </table>
      </div>

      <h2>Remote Access Issues</h2>

      <h3>Can't Connect from Another Device</h3>
      <p>If other devices on your network can't reach Uplink:</p>
      <ol>
        <li>Verify both devices are on the same Wi-Fi / LAN (or both on Tailscale)</li>
        <li><strong>Check that Uplink is bound to <code>0.0.0.0</code></strong> — by default it only listens on localhost. Enable <strong>Network Access</strong> in <strong>Settings → Server</strong>, or set <code>UPLINK_HOST=0.0.0.0</code> in your environment or <code>.env</code> file. Enabling authentication (<code>UPLINK_AUTH_ENABLED=true</code>) also automatically binds to <code>0.0.0.0</code>. See <a href="remote-access.html#network-binding">Network Binding</a>.</li>
        <li>Check your firewall (see <a href="remote-access.html">Remote Access</a>)</li>
        <li>Try using the IP address directly — not hostname</li>
        <li>Make sure you're using port 3456 (or 3457 for Tailscale HTTPS)</li>
        <li>If exposing to untrusted networks, enable authentication: set <code>UPLINK_AUTH_ENABLED=true</code> and <code>UPLINK_AUTH_TOKEN=&lt;your-long-random-token&gt;</code></li>
      </ol>

      <h3>Page Loads But "No Response Received"</h3>
      <p>If you can see the Uplink UI and send messages, but responses never come back:</p>
      <p>This usually means <code>GATEWAY_URL</code> in your <code>.env</code> file is set to a non-localhost address (like your Tailscale IP). The OpenClaw gateway only listens on <code>127.0.0.1</code>, so Uplink can't proxy your messages to it.</p>

      <div class="code-block">
        <div class="code-block-header">
          <span>.env</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code># ✅ Correct
GATEWAY_URL=http://127.0.0.1:23248

# ❌ Wrong — causes "No response received"
GATEWAY_URL=http://100.85.40.53:23248</code></pre>
      </div>

      <p>The gateway URL should <strong>always</strong> be localhost, even when accessing Uplink remotely. Uplink handles the proxying — remote clients talk to Uplink, and Uplink talks to the gateway locally.</p>

      <h3>WebSocket Disconnections</h3>
      <p>If conversations stop syncing or the UI shows "disconnected":</p>
      <ul>
        <li>Refresh the page — WebSocket will reconnect automatically</li>
        <li>If using Tailscale, check that the VPN tunnel is active</li>
        <li>Unstable Wi-Fi can cause frequent disconnects — try a wired connection</li>
      </ul>

      <h2>Encryption Issues</h2>

      <h3>Forgot Encryption Password</h3>
      <p>If you enabled encryption and forgot your password, <strong>your conversations cannot be recovered</strong>. This is by design — zero-knowledge encryption means the server cannot decrypt your data.</p>
      <p>Your options:</p>
      <ul>
        <li>If you have a backup of the database from before encryption, restore it</li>
        <li>Reset the database and start fresh (you'll lose all encrypted conversations)</li>
      </ul>

      <div class="callout warning">
        <strong>⚠ No Recovery</strong>
        Uplink's encryption is intentionally unrecoverable without the password. Store your password in a password manager.
      </div>

      <h2>Browser Compatibility</h2>
      <p>Uplink works in all modern browsers. Known quirks:</p>

      <div class="table-wrap">
        <table>
          <thead>
            <tr><th>Browser</th><th>Status</th><th>Notes</th></tr>
          </thead>
          <tbody>
            <tr><td><strong>Chrome / Edge</strong></td><td>✅ Full support</td><td>Best Web Speech API for native STT</td></tr>
            <tr><td><strong>Firefox</strong></td><td>✅ Full support</td><td>No native STT — use faster-whisper instead</td></tr>
            <tr><td><strong>Safari</strong></td><td>✅ Full support</td><td>PWA works on iOS 16.4+</td></tr>
            <tr><td><strong>Mobile Chrome</strong></td><td>✅ Full support</td><td>Best mobile experience as PWA</td></tr>
            <tr><td><strong>Mobile Safari</strong></td><td>✅ Full support</td><td>Add to Home Screen for PWA</td></tr>
          </tbody>
        </table>
      </div>

      <h2>Crash Recovery</h2>
      <p>Uplink includes a built-in <strong>watchdog</strong> that automatically restarts the server if it crashes unexpectedly. If you notice Uplink went down and came back on its own, the watchdog handled it. Check the server logs for crash details — the watchdog logs restart events so you can investigate the root cause.</p>

      <h2>Session Keys &amp; Multi-Platform</h2>

      <h3>Why doesn't my agent remember what I said on Telegram/Discord?</h3>
      <p>Each messaging platform gets its own <strong>session key</strong>, which means its own separate conversation history. Uplink uses the session key <code>agent:main:main</code>, which is shared with the OpenClaw Dashboard — so those two stay in sync. But Telegram, Discord, and other channels each have their own session keys and their own history.</p>
      <p>This means your agent on Telegram has no idea what you said on Uplink, and vice versa.</p>

      <p><strong>The fix: workspace memory files.</strong></p>
      <p>Workspace files like <code>MEMORY.md</code> and <code>AGENTS.md</code> are injected into <em>every</em> session regardless of platform. If your agent writes progress and decisions to files instead of just keeping them in conversation context, switching platforms is seamless.</p>

      <p><strong>Quick approach:</strong></p>
      <ol>
        <li>Tell your agent: <em>"After completing any task, write a summary to <code>memory/YYYY-MM-DD.md</code>. Always check memory files before answering questions about project status."</em></li>
        <li>Before switching platforms, tell your agent: <em>"memdump"</em> — this saves current context to a file.</li>
        <li>When you open the other platform, your agent reads the workspace files and picks up where you left off.</li>
      </ol>

      <div class="callout">
        <strong>Why it works this way:</strong> Separate session keys are intentional. You wouldn't want your Telegram messages showing up in your Uplink history or vice versa — they're different interfaces with different message formats. Workspace files are the bridge that carries context across all of them.
      </div>

      <h3>How do satellite sessions work?</h3>
      <p>Your primary Uplink chat uses the session key <code>agent:main:main</code> — the same key the OpenClaw Dashboard uses, so conversation history stays in sync between the two.</p>
      <p>Satellite sessions (additional chat tabs in Uplink) get isolated keys like <code>agent:main:uplink:satellite:&lt;id&gt;</code>. Each satellite has its own conversation history, independent of the main session and each other.</p>

      <h2>Artifacts Setup</h2>

      <h3>How do I set up Artifacts?</h3>
      <p>Artifacts is Uplink's built-in document viewer for agent-generated files — PRDs, reports, code, notes, anything your agent creates. It shows up as a panel you can browse, search, and read without leaving the chat.</p>

      <p><strong>Where does it look for files?</strong></p>
      <p>Uplink checks these locations in order and uses the first one it finds:</p>
      <ol>
        <li><code>ARTIFACTS_DIR</code> environment variable (if set)</li>
        <li><code>artifacts/</code> in the parent directory of your Uplink install (the OpenClaw workspace)</li>
        <li><code>artifacts/</code> inside the Uplink directory itself</li>
      </ol>

      <p><strong>Quick setup:</strong></p>
      <p>Create an <code>artifacts/</code> folder in your OpenClaw workspace and tell your agent to use it:</p>

      <div class="code-block">
        <div class="code-block-header">
          <span>directory structure</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code>workspace/
├── openclaw.json
├── AGENTS.md
├── MEMORY.md
├── artifacts/        ← agent writes docs here
│   ├── prd.md
│   ├── design-spec.md
│   └── weekly-report.md
└── uplink/
    └── (uplink files)</code></pre>
      </div>

      <p>Then tell your agent:</p>
      <blockquote>"When you create documents, reports, PRDs, or any reference files, save them to the <code>artifacts/</code> directory. Use descriptive filenames like <code>project-prd.md</code> or <code>api-design.md</code>."</blockquote>

      <p>Or add it to your <code>AGENTS.md</code>:</p>

      <div class="code-block">
        <div class="code-block-header">
          <span>AGENTS.md</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code>## Artifacts
- Save all generated documents to `artifacts/`
- Use descriptive filenames (e.g., `project-prd.md`, not `doc1.md`)
- Supported formats: .md, .txt, .html, .json, .csv, .yml, .yaml, .xml, .log</code></pre>
      </div>

      <p><strong>Custom location:</strong></p>
      <p>If you want artifacts stored somewhere else, set the <code>ARTIFACTS_DIR</code> environment variable:</p>

      <div class="code-block">
        <div class="code-block-header">
          <span>.env</span>
          <button class="copy-btn">Copy</button>
        </div>
        <pre><code># In your .env or shell profile
ARTIFACTS_DIR=/path/to/my/docs</code></pre>
      </div>

      <p><strong>What shows up in Artifacts?</strong></p>
      <p>Only text-based files with these extensions: <code>.md</code>, <code>.txt</code>, <code>.html</code>, <code>.json</code>, <code>.csv</code>, <code>.yml</code>, <code>.yaml</code>, <code>.xml</code>, <code>.log</code>. Binary files, images, and other formats are excluded for security.</p>

      <div class="callout">
        <strong>Pro tip:</strong> Artifacts works great with the workspace memory pattern. Your agent writes a report to <code>artifacts/weekly-summary.md</code>, and you can read it from any platform — Uplink, Telegram, Discord — because it's a file, not a chat message.
      </div>

      <h2>Getting Help</h2>
      <p>If none of the above resolves your issue:</p>
      <ol>
        <li>Check the browser console (F12 → Console) for error messages</li>
        <li>Check the Node.js terminal output for server-side errors</li>
        <li>Open an issue on <a href="https://github.com/mooncompany/uplink" target="_blank">GitHub</a> with:
          <ul>
            <li>Your OS and Node.js version</li>
            <li>Steps to reproduce the issue</li>
            <li>Any error messages from the browser console or server terminal</li>
          </ul>
        </li>
        <li>Join the <a href="https://discord.gg/mooncompany" target="_blank">Discord server</a> for community support</li>
      </ol>

      <div class="docs-footer">
        <p>UPLINK Docs — Built by <a href="https://moonco.pro" target="_blank">Moon Company</a>. Open source under MIT.</p>
      </div>
    </main>
  </div>

  <script src="js/docs.js"></script>
</body>
</html>

